version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_backend_clustered
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: redis_prod
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-BekkhnN017} --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
